import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { neue_montreal } from "@/utils/fonts";
import Navbar from "@/components/Navbar/";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${neue_montreal} font-neue-montreal`}>
        <Navbar />
        <div className="">{children}</div>
      </body>
    </html>
  );
}
